/* ============================================================================
   Copy the browser's own bpm.js and season.js into the Edge Function runtime.

   THE POINT IS THAT THERE IS ONE IMPLEMENTATION. The season awards are now
   decided by BPM, and BPM is four hundred lines of coefficients, position
   estimation and a team adjustment that is easy to get subtly wrong — this
   project has already been bitten once by exactly that, in the Python it was
   ported from. Writing it a second time in plpgsql so the database could pick
   an MVP would guarantee that one day the league page and the API name
   different players and both be able to show their working.

   So the file the Edge Function runs IS the file the browser runs, with an ESM
   tail bolted on: the UMD half attaches to globalThis, and the tail re-exports
   the same object so `import` works under Deno. That is the same arrangement
   _shared/engine.js already uses.

     node supabase/tests/extract-shared.mjs           # regenerate
     node supabase/tests/extract-shared.mjs --check   # fail if they have drifted

   Run the plain form after editing league/bpm.js or league/season.js. CI runs
   --check, so a drift is a failed build rather than a wrong MVP six weeks from
   now.
   ============================================================================ */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');

const FILES = [
  {
    src: join(repo, 'league', 'bpm.js'),
    out: join(repo, 'supabase', 'functions', '_shared', 'bpm.js'),
    global: 'EpinoiaBPM',
    names: ['forLeague', 'forTeam', 'teamInputs', 'estimatedPossessions', 'per100',
            'estimatePosition', 'estimateOffensiveRole', 'rawBPM',
            'positionConstant', 'teamAdjustment', 'lerp']
  },
  {
    src: join(repo, 'league', 'season.js'),
    out: join(repo, 'supabase', 'functions', '_shared', 'season.js'),
    global: 'EpinoiaSeason',
    names: ['players', 'teams', 'percentiles', 'teamLine', 'attachBPM', 'POSS']
  }
];

const tail = (f) => `
/* ---------------------------------------------------------------------------
   GENERATED TAIL — do not edit this file. Edit the browser copy and re-run
   \`node supabase/tests/extract-shared.mjs\`; CI fails if the two drift.

   The UMD half above attaches to globalThis; this re-exports the same object
   so the Edge Function and the browser run one identical file.
   --------------------------------------------------------------------------- */
const __api = globalThis.${f.global};
export const { ${f.names.join(', ')} } = __api;
export default __api;
`;

const banner = (name) =>
  `/* GENERATED from league/${name} by supabase/tests/extract-shared.mjs — do not edit. */\n`;

const build = (f) => banner(f.src.split(/[\\/]/).pop()) + readFileSync(f.src, 'utf8') + tail(f);

const check = process.argv.includes('--check');
let drifted = 0;

for (const f of FILES) {
  const want = build(f);
  const have = existsSync(f.out) ? readFileSync(f.out, 'utf8') : null;
  const rel = f.out.replace(repo, '').replace(/^[\\/]/, '');
  if (have === want) { console.log(`  ok       ${rel}`); continue; }
  if (check) {
    drifted++;
    console.error(`  DRIFTED  ${rel}\n           ` +
      (have === null ? 'it does not exist' : 'it no longer matches the browser copy') +
      ' — run: node supabase/tests/extract-shared.mjs');
    continue;
  }
  writeFileSync(f.out, want);
  console.log(`  written  ${rel}`);
}

if (check && drifted) {
  console.error(`\n${drifted} shared file(s) out of date with league/.`);
  process.exit(1);
}
console.log(check ? '\nshared modules match the browser copies'
                  : '\nshared modules regenerated');
