/* GENERATED from epinoia/features.js by supabase/tests/extract-shared.mjs — do not edit. */
'use strict';
/* ============================================================================
   THE FEATURE LINE (What wins 2, docs/what-wins-model.md §3): every finished game
   reduced ONCE to 108 counts per side, so the model never reads a raw event log.

   Run in two places and nowhere else: finalise-game (supabase/functions/_shared/
   features.js is this file, generated by supabase/tests/extract-shared.mjs) and the
   one-off backfill (scripts/backfill_features.mjs). The rows land in game_features,
   which only the service role can read; the browser never sees a line.

   ONE CALCULATOR PER QUESTION. The box counts are teamAdv's, the possessions and their
   clock ShotClock's, the situations situations.js's, the zone counts the engine's own
   rim rule (adv.rimA, 125 cm, marker first, then type). What is new here is only what
   no file answered before: free-throw trips and what they were for, live and dead
   turnovers, the bonus, clutch and garbage possessions, runs and lead changes, and the
   rotation's shape. Those come from this file's own walk of the log; the engine,
   possessions.js, situations.js and shotclock.js are read, never edited.

     extract(game, {d, TA, C})   -> {fv, f: [Float64Array(108) x2], q: [bits x2], st: [stints x2]}
     toRows(gameId, out, meta)   -> the two game_features rows (4 significant figures, NaN -> null)
     fromRow(row)                -> Float64Array(108), null -> NaN
     derive(own, opp, qO, qX)    -> {factor: value | null} for one game
     seasonFactors(pairs)        -> {factor: {v, n}}: ratios of sums, never means of ratios
     valid(vector)               -> true when the counts are internally consistent

   NEVER THROWS ON A THIN FEED. A section that cannot be worked out is left NaN and its
   quality bit cleared, so a model can see what it may use. FV is the layout's version:
   a new or moved index is FV 2 (§3.7).
   ============================================================================ */
(function (root, factory) {
  const api = factory(root);
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.EpinoiaFeatures = api;
}(typeof globalThis !== 'undefined' ? globalThis : self, function (root) {

/* the calculators: globals on a page and in Deno (imported first, for their side effect), modules in node.
   Asked for when extract() runs, never at load, so the import order of the Edge Function does not matter. */
const dep = (g, file) => root[g] || (typeof require === 'function' ? (() => { try { return require('./' + file); } catch (_) { return null; } })() : null);
const Engine = () => dep('EpinoiaEngine', 'engine.js');
const Poss = () => dep('EpinoiaPossessions', 'possessions.js');
const Clock = () => dep('EpinoiaShotClock', 'shotclock.js');
const Sit = () => dep('EpinoiaSituations', 'situations.js');

const FV = 1;

/* quality bits (§3.4): what this game's feed can support */
const QBITS = Object.freeze({ MARK: 1, TYPE: 2, ZONES: 4, TIMED: 8, SIT: 16, STYPE: 32, FOULKIND: 64, STARTERS: 128, STL: 256, DENSE: 512 });
const B = QBITS;

/* ---------------------------------------------------------------- layout (§3.3) ---
   [key, agg ('sum' | 'mean'), side ('own' | 'game'), pub, need bits, unit]. The order IS the format: a row's
   f[i] is LAYOUT[i]. Never reorder or insert; append and bump FV. */
const L = (k, o) => Object.assign({ k, agg: 'sum', side: 'own', pub: false, need: 0, unit: 'n' }, o || {});
const PUB = { pub: true };
const LAYOUT = Object.freeze([
  // 0-26 box, from teamAdv and the engine's team line
  L('pts', { pub: true, unit: 'pts' }), L('fga', PUB), L('fgm', PUB), L('fg3a', PUB), L('fg3m', PUB), L('fta', PUB), L('ftm', PUB),
  L('oreb', PUB), L('dreb', PUB), L('tov', PUB), L('ast', PUB), L('stl', PUB), L('blk', PUB),
  L('rim_a', { pub: true, need: B.ZONES }), L('rim_m', { pub: true, need: B.ZONES }),
  L('mid_a', { pub: true, need: B.ZONES }), L('mid_m', { pub: true, need: B.ZONES }),
  L('poss_est', PUB), L('minutes', { pub: true, side: 'game', unit: 'min' }),
  L('pts_paint', { pub: true, unit: 'pts' }), L('pts_fast', { pub: true, unit: 'pts' }), L('pts_second', { pub: true, unit: 'pts' }),
  L('pts_offto', { pub: true, unit: 'pts' }), L('pts_bench', { pub: true, unit: 'pts' }),
  L('fouls', PUB), L('timeouts', PUB), L('max_lead', { pub: true, agg: 'mean', unit: 'pts' }),
  // 27-42 possessions and time (ShotClock / Possessions)
  L('poss'), L('chances'), L('poss_3q'), L('reg_min', { side: 'game', unit: 'min' }), L('gain_dreb'),
  L('timed_n'), L('timed_s', { need: B.TIMED, unit: 's' }), L('fc_n', { need: B.TIMED }),
  L('fc_e_n', { need: B.TIMED }), L('fc_e_pts', { need: B.TIMED, unit: 'pts' }),
  L('fc_m_n', { need: B.TIMED }), L('fc_m_pts', { need: B.TIMED, unit: 'pts' }),
  L('fc_l_n', { need: B.TIMED }), L('fc_l_pts', { need: B.TIMED, unit: 'pts' }),
  L('reb_off_ch'), L('reb_def_ch'),
  // 43-56 situations (situations.js)
  L('sit_ch', { need: B.SIT }), L('tr_ch', { need: B.SIT }), L('tr_pts', { need: B.SIT, unit: 'pts' }),
  L('hc_ch', { need: B.SIT }), L('hc_pts', { need: B.SIT, unit: 'pts' }),
  L('sc_ch', { need: B.SIT }), L('sc_pts', { need: B.SIT, unit: 'pts' }),
  L('offto_ch', { need: B.SIT }), L('offto_pts', { need: B.SIT, unit: 'pts' }),
  L('ato_n', { need: B.SIT }), L('ato_pts', { need: B.SIT, unit: 'pts' }),
  L('fgm_ast', { need: B.SIT }), L('fgm_unast', { need: B.SIT }), L('fg3m_ast', { need: B.SIT }),
  // 57-62 turnovers
  L('to_n'), L('to_live', { need: B.STL }), L('to_typed'), L('to_badpass', { need: B.STYPE }), L('to_handle', { need: B.STYPE }),
  L('to_offfoul', { need: B.FOULKIND }),
  // 63-70 fouls and free throws
  L('fouls_shooting', { need: B.FOULKIND }), L('fouls_offensive', { need: B.FOULKIND }), L('techs'), L('ft_trips'), L('and1'),
  L('trips_shooting', { need: B.FOULKIND }), L('trips_bonus', { need: B.FOULKIND }), L('fta_bonus', { need: B.FOULKIND }),
  // 71-80 flow (own walk)
  L('lead_changes', { side: 'game', agg: 'mean' }), L('ties', { side: 'game', agg: 'mean' }), L('lead_ms', { unit: 'ms' }),
  L('max_deficit', { agg: 'mean', unit: 'pts' }), L('best_run', { agg: 'mean', unit: 'pts' }), L('runs8'),
  L('pts_h1', { unit: 'pts' }), L('pts_h2', { unit: 'pts' }), L('pts_ot', { unit: 'pts' }), L('ot_periods', { side: 'game' }),
  // 81-86 clutch possessions
  L('cl_poss'), L('cl_pts', { unit: 'pts' }), L('cl_tov'), L('cl_fga'), L('cl_efgm'), L('cl_fta'),
  // 87-95 competitive (non-garbage) possessions
  L('g_poss'), L('c_pts', { unit: 'pts' }), L('c_fga'), L('c_efgm'), L('c_fta'), L('c_ftm'), L('c_tov'), L('c_reb_off'), L('c_reb_def'),
  // 96-104 rotation
  L('players_used', { agg: 'mean' }), L('rot_n', { agg: 'mean' }), L('top5_min_share', { agg: 'mean', unit: 'share' }),
  L('starters_min_share', { agg: 'mean', unit: 'share', need: B.STARTERS }), L('usg_hhi', { agg: 'mean', unit: 'index' }),
  L('top_usg_share', { agg: 'mean', unit: 'share' }), L('fives_used', { agg: 'mean' }), L('top_five_share', { agg: 'mean', unit: 'share' }),
  L('starters_net', { need: B.STARTERS, unit: 'pts' }),
  // 105-107 quality
  L('events', { side: 'game' }), L('zoned_2pa'), L('sit_rim_a', { need: B.SIT })
].map((x, i) => Object.freeze(Object.assign({ i }, x))));
const N = LAYOUT.length;                                   // 108
const INDEX = Object.freeze(LAYOUT.reduce((o, x) => { o[x.k] = x.i; return o; }, {}));
const I = INDEX;
const MEAN = LAYOUT.filter(x => x.agg === 'mean').map(x => x.i);

/* clutch and garbage time (§3.2) */
const CLUTCH_MS = 300000, CLUTCH_MARGIN = 5;
const GARBAGE = Object.freeze([Object.freeze([480000, 20]), Object.freeze([240000, 13])]);   // [remaining ms ≤, |margin| ≥]
/* team fouls from which a personal foul gives free throws, by the number of periods */
const BONUS = Object.freeze({ 4: 5, 2: 7 });
const bonusAt = periods => BONUS[periods] || 5;

/* ------------------------------------------------------------------ extract --- */
const DESCRIPTOR = { loc: 1, tag: 1, stype: 1 };
const PTS = { ft_made: 1, p2_made: 2, p3_made: 3 };
const FGA = { p2_made: 1, p2_miss: 1, p3_made: 1, p3_miss: 1 };
const seqOf = ev => (ev.seq != null ? ev.seq : ev.id);
const side = t => t === 0 || t === 1;
const RX_PASS = /pass/i, RX_HANDLE = /travel|dribbl|carr|palm|handl/i, RX_OFFFOUL = /offensive|charg/i;
const TRIP_GAP = new Set(['sub', 'timeout', 'foul', 'ast']);

function blank() { const a = new Float64Array(N); a.fill(NaN); return a; }

function extract(game, pre) {
  pre = pre || {};
  const out = { fv: FV, f: [blank(), blank()], q: [0, 0], st: [null, null] };
  const f = out.f;
  if (!game || !Array.isArray(game.teams) || game.teams.length < 2) return out;
  const E = Engine(), P = Poss(), SCm = Clock(), X = Sit();
  const events = (game.events || []).filter(Boolean);

  let d = pre.d || null, TA = pre.TA || null;
  try { if (!d && E) d = E.deriveGame(game); } catch (_) { d = null; }
  try { if (d && !TA && E) TA = [E.teamAdv(game, d, 0), E.teamAdv(game, d, 1)]; } catch (_) { TA = null; }
  const F = (d && d.format) || (E ? E.formatOf(game) : { periods: 4, period_ms: 600000, ot_ms: 300000 });
  const PLEN = p => (p <= F.periods ? F.period_ms : F.ot_ms);
  const cum = (p, clk) => { let s = 0; for (let k = 1; k < p; k++) s += PLEN(k); return s + (PLEN(p) - clk); };
  const REG_MS = F.periods * F.period_ms;
  const stypes = (d && d.stypes) || {}, locs = (d && d.locs) || {};

  /* the log as every calculator reads it: game order, descriptors out */
  let all = events;
  try { if (X && X.inGameOrder) all = X.inGameOrder(events); } catch (_) { all = events; }
  const plays = all.filter(ev => ev && !DESCRIPTOR[ev.t]);

  const set = (t, k, v) => { f[t][I[k]] = v; };
  const both = (k, v) => { f[0][I[k]] = v; f[1][I[k]] = v; };

  /* ---- 0-26 the box: teamAdv and the engine's team line ---- */
  if (d && TA) {
    try {
      [0, 1].forEach(t => {
        const A = TA[t], T = d.team[t];
        const vals = { pts: A.pts, fga: A.fga, fgm: A.fgm, fg3a: A.fg3a, fg3m: A.fg3m, fta: A.fta, ftm: A.ftm, oreb: A.oreb,
          dreb: A.dreb, tov: A.tov, ast: A.ast, stl: A.stl, blk: A.blk, rim_a: A.rimA, rim_m: A.rimM, mid_a: A.midA, mid_m: A.midM,
          poss_est: A.possessions, minutes: A.minutes / 5, pts_paint: T.paint, pts_fast: T.fast, pts_second: T.sc, pts_offto: T.pot,
          pts_bench: T.bench, fouls: T.foulTot,
          timeouts: (T.tos.h1 || 0) + (T.tos.h2 || 0) + Object.values(T.tos.ot || {}).reduce((a, b) => a + b, 0),
          max_lead: T.lead };
        Object.keys(vals).forEach(k => set(t, k, +vals[k]));
      });
    } catch (_) { /* left NaN */ }
  }

  /* ---- 27-42 possessions and time ---- */
  both('reg_min', REG_MS / 60000);
  let SC = null, PZ = null;
  try { if (SCm && P) { SC = SCm.compute({ events }); PZ = P.enumerate({ events: plays }); } } catch (_) { SC = null; }
  const timedOk = [false, false];
  if (SC && SC.ok && PZ) {
    try {
      [0, 1].forEach(t => {
        const ps = SC.possessions.filter(p => p.team === t), cs = SC.chances.filter(c => c.team === t);
        const timed = ps.filter(p => p.dur != null);
        const first = cs.filter(c => !c.second && c.dur != null);
        const win = (lo, hi) => first.filter(c => c.dur > lo && c.dur <= hi);
        const e = first.filter(c => c.dur <= 8), m = win(8, 16), l = first.filter(c => c.dur > 16);
        const sum = (a, k) => a.reduce((n, x) => n + (x[k] || 0), 0);
        set(t, 'poss', ps.length); set(t, 'chances', cs.length);
        set(t, 'poss_3q', ps.filter(p => { const g = PZ.possessions[p.index]; return g && cum(g.gainPeriod, g.gainClock) < 0.75 * REG_MS; }).length);
        set(t, 'gain_dreb', ps.filter(p => p.gainedBy === 'dreb').length);
        set(t, 'timed_n', timed.length); set(t, 'timed_s', sum(timed, 'dur'));
        set(t, 'fc_n', first.length);
        set(t, 'fc_e_n', e.length); set(t, 'fc_e_pts', sum(e, 'pts'));
        set(t, 'fc_m_n', m.length); set(t, 'fc_m_pts', sum(m, 'pts'));
        set(t, 'fc_l_n', l.length); set(t, 'fc_l_pts', sum(l, 'pts'));
        set(t, 'reb_off_ch', cs.filter(c => c.reb === 'off').length);
        set(t, 'reb_def_ch', cs.filter(c => c.reb === 'def').length);
        timedOk[t] = ps.length > 0 && timed.length >= 0.7 * ps.length;
      });
    } catch (_) { SC = null; }
  }

  /* ---- 43-56 situations ---- */
  let C = pre.C || null;
  try { if (!C && X) C = X.compute({ teams: game.teams, events }); } catch (_) { C = null; }
  const sitOk = !!(C && C.possessions && C.side);
  if (sitOk) {
    try {
      [0, 1].forEach(t => {
        const S = C.side[t].sits, A = C.side[t].assists || { ast: {}, unast: {} };
        set(t, 'sit_ch', S.all.chances);
        set(t, 'tr_ch', S.transition.chances); set(t, 'tr_pts', S.transition.pts);
        set(t, 'hc_ch', S.half.chances); set(t, 'hc_pts', S.half.pts);
        set(t, 'sc_ch', S.second.chances); set(t, 'sc_pts', S.second.pts);
        set(t, 'offto_ch', S.offTo.chances); set(t, 'offto_pts', S.offTo.pts);
        set(t, 'ato_n', S.ato.chances); set(t, 'ato_pts', S.ato.pts);
        set(t, 'fgm_ast', +A.ast.fgm || 0); set(t, 'fgm_unast', +A.unast.fgm || 0); set(t, 'fg3m_ast', +A.ast.p3m || 0);
        set(t, 'sit_rim_a', S.all.zones.rim.a);
      });
    } catch (_) { /* left NaN */ }
  }

  /* ---- 57-80 this file's own walk: turnovers, fouls, free throws, the score ---- */
  const q = [0, 0];
  let foulKindOk = false, anyStl = false, dense = plays.length > 0;
  try {
    const n = plays.length;
    const near = (i, lo, hi, pred) => { for (let j = Math.max(0, i + lo); j <= Math.min(n - 1, i + hi); j++) if (j !== i && pred(plays[j], j)) return j; return -1; };
    const close = (a, b, ms) => a.period === b.period && Math.abs((+a.clock || 0) - (+b.clock || 0)) <= ms;

    /* team fouls as the engine keys them: bench technicals out, overtime in the last period */
    const tf = [{}, {}], foulCount = new Map();
    let fouls = 0, kinded = 0, shootingSeen = false;
    plays.forEach(ev => {
      if (ev.t === 'stl') anyStl = true;
      if (ev.t !== 'foul') return;
      fouls++; if (ev.kind) kinded++; if (ev.kind === 'shooting') shootingSeen = true;
      if (!side(ev.team)) return;
      if (!(ev.kind === 'tech' && !ev.pid)) { const key = ev.period > F.periods ? F.periods : ev.period; tf[ev.team][key] = (tf[ev.team][key] || 0) + 1; }
      foulCount.set(ev, tf[ev.team][ev.period > F.periods ? F.periods : ev.period] || 0);
    });
    foulKindOk = shootingSeen && fouls > 0 && kinded >= 0.9 * fouls;

    const c = [0, 1].map(() => ({ to_n: 0, to_live: 0, to_typed: 0, to_badpass: 0, to_handle: 0, to_offfoul: 0,
      fouls_shooting: 0, fouls_offensive: 0, techs: 0, ft_trips: 0, and1: 0, trips_shooting: 0, trips_bonus: 0, fta_bonus: 0 }));
    plays.forEach((ev, i) => {
      if (!side(ev.team)) return;
      const t = ev.team;
      if (ev.t === 'to') {
        const C0 = c[t]; C0.to_n++;
        const ty = stypes[ev.id] || '';
        if (ty) { C0.to_typed++; if (RX_PASS.test(ty)) C0.to_badpass++; if (RX_HANDLE.test(ty)) C0.to_handle++; }
        if (near(i, -2, 3, x => x.t === 'stl' && x.team === 1 - t && close(x, ev, 2000)) >= 0) C0.to_live++;
        if ((ty && RX_OFFFOUL.test(ty)) || near(i, -2, 2, x => x.t === 'foul' && x.kind === 'offensive' && x.team === t && close(x, ev, 1000)) >= 0) C0.to_offfoul++;
      } else if (ev.t === 'foul') {
        if (ev.kind === 'shooting') c[t].fouls_shooting++;
        if (ev.kind === 'offensive') c[t].fouls_offensive++;
        if (ev.kind === 'tech' || ev.kind === 'unsport') c[t].techs++;
      }
    });

    /* FREE-THROW TRIPS: one team, one shooter, one period, within a second, with only a sub, a timeout, a foul or
       an assist between (FIBA logs an assist between free throws). Then the foul that sent him there, the other
       side's nearest by index within six plays, and whether it was an and-one or the bonus. */
    const inTrip = new Set(), usedFoul = new Set();
    for (let i = 0; i < n; i++) {
      const ev = plays[i];
      if (!(ev.t === 'ft_made' || ev.t === 'ft_miss') || inTrip.has(i) || !side(ev.team)) continue;
      const trip = [i]; inTrip.add(i);
      let last = ev;
      for (let j = i + 1; j < n; j++) {
        const x = plays[j];
        if ((x.t === 'ft_made' || x.t === 'ft_miss') && x.team === ev.team && (x.pid || null) === (ev.pid || null) &&
            x.period === ev.period && Math.abs((+x.clock || 0) - (+last.clock || 0)) <= 1000 && !inTrip.has(j)) {
          trip.push(j); inTrip.add(j); last = x; continue;
        }
        if (TRIP_GAP.has(x.t)) continue;
        break;
      }
      const t = ev.team, C0 = c[t];
      C0.ft_trips++;
      let best = -1;
      for (let j = Math.max(0, i - 6); j <= Math.min(n - 1, i + 6); j++) {
        const x = plays[j];
        if (x.t !== 'foul' || x.team !== 1 - t || usedFoul.has(j) || !close(x, ev, 1000)) continue;
        if (best < 0 || Math.abs(j - i) < Math.abs(best - i)) best = j;
      }
      const foul = best >= 0 ? plays[best] : null;
      if (best >= 0) usedFoul.add(best);
      const kind = foul ? (foul.kind || 'personal') : 'none';
      let and1 = false;
      if (trip.length === 1 && (kind === 'shooting' || kind === 'none')) {
        and1 = near(i, -4, 4, x => (x.t === 'p2_made' || x.t === 'p3_made') && x.team === t &&
          (!x.pid || !ev.pid || x.pid === ev.pid) && close(x, ev, 1000)) >= 0;
      }
      if (and1) C0.and1++;
      else if (kind === 'shooting') C0.trips_shooting++;
      if (kind === 'personal' && (foulCount.get(foul) || 0) >= bonusAt(F.periods)) { C0.trips_bonus++; C0.fta_bonus += trip.length; }
    }
    [0, 1].forEach(t => Object.keys(c[t]).forEach(k => set(t, k, c[t][k])));

    /* THE SCORE AS IT MOVED: lead changes, ties, time ahead, the worst deficit, runs */
    const s = [0, 0], leadMs = [0, 0], deficit = [0, 0], bestRun = [0, 0], runs8 = [0, 0];
    let leader = -1, changes = 0, ties = 0, lastCum = 0, runSide = -1, runPts = 0, runCounted = false;
    plays.forEach(ev => {
      const v = PTS[ev.t];
      if (!v || !side(ev.team)) return;
      const at = cum(ev.period || 1, ev.clock != null ? +ev.clock : PLEN(ev.period || 1));
      if (isFinite(at)) {
        if (s[0] > s[1]) leadMs[0] += Math.max(0, at - lastCum); else if (s[1] > s[0]) leadMs[1] += Math.max(0, at - lastCum);
        lastCum = Math.max(lastCum, at);
      }
      const t = ev.team;
      s[t] += v;
      if (s[0] !== s[1]) {
        const now = s[0] > s[1] ? 0 : 1;
        if (leader >= 0 && now !== leader) changes++;
        leader = now;
      } else if (s[0] > 0) ties++;
      deficit[0] = Math.max(deficit[0], s[1] - s[0]); deficit[1] = Math.max(deficit[1], s[0] - s[1]);
      if (runSide === t) runPts += v; else { runSide = t; runPts = v; runCounted = false; }
      bestRun[t] = Math.max(bestRun[t], runPts);
      if (runPts >= 8 && !runCounted) { runs8[t]++; runCounted = true; }
    });
    const lastPeriod = Math.max(+game.period || 1, ...plays.map(ev => +ev.period || 1));
    const endCum = Math.max(lastCum, cum(+game.period || lastPeriod, game.clockMs != null ? +game.clockMs : 0));
    if (isFinite(endCum)) { if (s[0] > s[1]) leadMs[0] += endCum - lastCum; else if (s[1] > s[0]) leadMs[1] += endCum - lastCum; }
    both('lead_changes', changes); both('ties', ties);
    both('ot_periods', Math.max(0, lastPeriod - F.periods));
    [0, 1].forEach(t => {
      set(t, 'lead_ms', leadMs[t]); set(t, 'max_deficit', deficit[t]); set(t, 'best_run', bestRun[t]); set(t, 'runs8', runs8[t]);
      if (d) {
        const pq = d.perQ[t] || {};
        let h1 = 0, h2 = 0, ot = 0;
        Object.keys(pq).forEach(p => { const k = +p, v = +pq[p] || 0; if (k <= F.periods / 2) h1 += v; else if (k <= F.periods) h2 += v; else ot += v; });
        set(t, 'pts_h1', h1); set(t, 'pts_h2', h2); set(t, 'pts_ot', ot);
      }
    });

    /* gaps: no play-free stretch over 90 s inside a period */
    for (let i = 1; i < n && dense; i++) {
      const a = plays[i - 1], b = plays[i];
      if (a.period === b.period && Math.abs((+a.clock || 0) - (+b.clock || 0)) > 90000) dense = false;
    }
    both('events', n);
  } catch (_) { /* left NaN; FOULKIND, STL and DENSE stay off */ foulKindOk = false; anyStl = false; dense = false; }

  /* ---- 81-95 clutch and competitive possessions: the margin when each began ---- */
  if (SC && SC.ok && PZ) {
    try {
      const before = new Map(), s = [0, 0];
      plays.forEach(ev => { const k = seqOf(ev); if (!before.has(k)) before.set(k, [s[0], s[1]]); const v = PTS[ev.t]; if (v && side(ev.team)) s[ev.team] += v; });
      const byPoss = new Map();
      SC.chances.forEach(ch => { const a = byPoss.get(ch.possession) || []; a.push(ch); byPoss.set(ch.possession, a); });
      const z = () => ({ cl_poss: 0, cl_pts: 0, cl_tov: 0, cl_fga: 0, cl_efgm: 0, cl_fta: 0, g_poss: 0, c_pts: 0, c_fga: 0, c_efgm: 0,
                         c_fta: 0, c_ftm: 0, c_tov: 0, c_reb_off: 0, c_reb_def: 0 });
      const c = [z(), z()];
      SC.possessions.forEach(p => {
        const t = p.team, g = PZ.possessions[p.index];
        if (!side(t) || !g) return;
        const start = cum(g.gainPeriod, g.gainClock);
        const ot = (g.gainPeriod || g.period) > F.periods;
        const rem = REG_MS - start;
        const sc = before.get(g.startEventId) || [NaN, NaN];
        const margin = Math.abs(sc[t] - sc[1 - t]);
        const chs = byPoss.get(p.index) || [];
        const tot = k => chs.reduce((a, x) => a + (x[k] || 0), 0);
        const C0 = c[t];
        if ((ot || rem <= CLUTCH_MS) && margin <= CLUTCH_MARGIN) {
          C0.cl_poss++; C0.cl_pts += tot('pts'); C0.cl_tov += tot('tov'); C0.cl_fga += tot('fga');
          C0.cl_efgm += tot('fgm') + 0.5 * tot('p3m'); C0.cl_fta += tot('fta');
        }
        const garbage = !ot && GARBAGE.some(([ms, m]) => rem <= ms && margin >= m);
        if (garbage) { C0.g_poss++; return; }
        C0.c_pts += tot('pts'); C0.c_fga += tot('fga'); C0.c_efgm += tot('fgm') + 0.5 * tot('p3m');
        C0.c_fta += tot('fta'); C0.c_ftm += tot('ftm'); C0.c_tov += tot('tov');
        C0.c_reb_off += chs.filter(x => x.reb === 'off').length; C0.c_reb_def += chs.filter(x => x.reb === 'def').length;
      });
      [0, 1].forEach(t => Object.keys(c[t]).forEach(k => set(t, k, c[t][k])));
    } catch (_) { /* left NaN */ }
  }

  /* ---- 96-104 rotation, and the compact stints (A.1) ---- */
  const startersOk = [0, 1].map(t => { const s = (game.starters && game.starters[t]) || []; return s.length === 5 && new Set(s).size === 5; });
  if (d) {
    [0, 1].forEach(t => {
      try {
        const ids = (game.teams[t].players || []).map(p => p.id);
        const mins = ids.map(id => (d.stats[id] && +d.stats[id].min) || 0);
        const tot = mins.reduce((a, b) => a + b, 0);
        const sorted = mins.slice().sort((a, b) => b - a);
        set(t, 'players_used', mins.filter(m => m > 0).length);
        set(t, 'rot_n', mins.filter(m => m >= 600000).length);
        set(t, 'top5_min_share', tot ? sorted.slice(0, 5).reduce((a, b) => a + b, 0) / tot : NaN);
        const starters = startersOk[t] ? game.starters[t] : [];
        set(t, 'starters_min_share', tot && startersOk[t] ? starters.reduce((a, id) => a + ((d.stats[id] && +d.stats[id].min) || 0), 0) / tot : NaN);
        const u = ids.map(id => { const s = d.stats[id]; return s ? s.p2a + s.p3a + 0.44 * s.fta + s.to : 0; });
        const U = u.reduce((a, b) => a + b, 0);
        set(t, 'usg_hhi', U ? 100 * u.reduce((a, x) => a + (x / U) * (x / U), 0) : NaN);
        set(t, 'top_usg_share', U ? Math.max(...u) / U : NaN);
        const stints = (d.lineups && d.lineups[t]) || [];
        const fives = new Map();
        let durAll = 0;
        stints.forEach(l => { if (!(l.dur > 0)) return; const k = l.ids.slice().sort().join(','); fives.set(k, (fives.get(k) || 0) + l.dur); durAll += l.dur; });
        set(t, 'fives_used', fives.size);
        set(t, 'top_five_share', durAll ? Math.max(...fives.values()) / durAll : NaN);
        const sk = starters.slice().sort().join(',');
        set(t, 'starters_net', startersOk[t] ? stints.filter(l => l.ids.slice().sort().join(',') === sk).reduce((a, l) => a + (l.pf - l.pa), 0) : NaN);
        /* A.1: every stint as [seconds, i1..i5] into this side's player list, for the builder's slot minutes */
        const list = ids.slice(), at = new Map(list.map((id, k) => [id, k]));
        const rows = [];
        stints.forEach(l => {
          if (!(l.dur > 0)) return;
          const ix = l.ids.map(id => { if (!at.has(id)) { at.set(id, list.length); list.push(id); } return at.get(id); });
          rows.push([Math.round(l.dur / 100) / 10].concat(ix));
        });
        out.st[t] = { p: list, s: rows };
      } catch (_) { /* left NaN */ }
    });
  }

  /* ---- 105-107 quality, and the bits ---- */
  const evOk = plays.length > 0;
  [0, 1].forEach(t => {
    let n2 = 0, marked = 0, zoned = 0, nfga = 0, typed = 0;
    plays.forEach(ev => {
      if (ev.team !== t || !FGA[ev.t]) return;
      nfga++;
      const ty = stypes[ev.id];
      if (ty) typed++;
      if (ev.t === 'p2_made' || ev.t === 'p2_miss') { n2++; if (locs[ev.id]) marked++; if (locs[ev.id] || ty) zoned++; }
    });
    if (evOk) set(t, 'zoned_2pa', zoned);
    let bits = 0;
    if (n2 > 0 && marked >= 0.8 * n2) bits |= B.MARK;
    if (nfga > 0 && typed >= 0.5 * nfga) bits |= B.TYPE;
    const ra = f[t][I.rim_a], sra = f[t][I.sit_rim_a];
    if (n2 > 0 && zoned >= 0.8 * n2 && isFinite(ra) && isFinite(sra) && Math.abs(ra - sra) <= Math.max(6, 0.4 * Math.max(ra, sra))) bits |= B.ZONES;
    if (timedOk[t]) bits |= B.TIMED;
    if (sitOk && isFinite(f[t][I.sit_ch])) bits |= B.SIT;
    const ton = f[t][I.to_n], tty = f[t][I.to_typed];
    if (ton > 0 && tty >= 0.7 * ton) bits |= B.STYPE;
    if (foulKindOk) bits |= B.FOULKIND;
    if (startersOk[t]) bits |= B.STARTERS;
    if (anyStl) bits |= B.STL;
    if (dense && evOk) bits |= B.DENSE;
    q[t] = evOk ? bits : 0;                                  // no log, nothing to vouch for
  });
  out.q = q;
  return out;
}

/* ------------------------------------------------------------------- rows --- */
const sig4 = v => (typeof v === 'number' && isFinite(v) ? (v === 0 ? 0 : +v.toPrecision(4)) : null);

/* the two game_features rows. meta = {league_id, season_id, competition_id, finalised_at} */
function toRows(gameId, out, meta) {
  meta = meta || {};
  return [0, 1].map(t => ({
    game_id: gameId, team_idx: t, fv: out.fv || FV,
    f: Array.from(out.f[t] || [], sig4),
    q: (out.q && out.q[t]) | 0,
    st: (out.st && out.st[t]) || null,
    league_id: meta.league_id, season_id: meta.season_id, competition_id: meta.competition_id,
    finalised_at: meta.finalised_at
  }));
}

function fromRow(row) {
  const a = blank();
  const src = (row && (row.f || row)) || [];
  for (let i = 0; i < Math.min(N, src.length); i++) { const v = src[i]; a[i] = v == null || v === '' ? NaN : +v; }
  return a;
}

/* ---------------------------------------------------------------- factors (§3.6) ---
   fn(o, x) reads two count vectors (own, opp) and returns a value or null. A zero denominator is null; a game
   whose rows lack the factor's need bits gives null. pg: a per-game count (season: the sum over the games used,
   divided by them). min: the smallest denominator worth a rate in one game. */
const R = (num, den, scale, min) => {
  if (!isFinite(num) || !isFinite(den) || den === 0 || (min && den < min)) return null;
  return (scale || 1) * num / den;
};
const V = v => (isFinite(v) ? v : null);
const FX = (k, label, grp, o) => Object.assign({ k, label, grp, unit: '%', dir: 1, side: 'own', need: 0, diff: true, score: false,
  pub: false, def: '', pg: false, min: 0, builder: false, fn: null }, o);
const efgm = a => a[I.fgm] + 0.5 * a[I.fg3m];

const FACTOR_LIST = [
  // four factors and shooting (diff, pub)
  FX('efg', 'eFG%', 'shooting', { pub: true, def: 'Effective field-goal %: (FGM + 0.5 × 3PM) / FGA', fn: o => R(efgm(o), o[I.fga], 100) }),
  FX('ts', 'TS%', 'shooting', { pub: true, def: 'True shooting %: points / (2 × (FGA + 0.44 × FTA))', fn: o => R(o[I.pts], 2 * (o[I.fga] + 0.44 * o[I.fta]), 100) }),
  FX('tovp', 'TOV%', 'turnovers', { pub: true, dir: -1, def: 'Turnovers per 100 plays: TOV / (FGA + 0.44 × FTA + TOV)', fn: o => R(o[I.tov], o[I.fga] + 0.44 * o[I.fta] + o[I.tov], 100) }),
  FX('orebp', 'OREB%', 'boards', { pub: true, def: 'Offensive rebound %: OREB / (OREB + opponent DREB)', fn: (o, x) => R(o[I.oreb], o[I.oreb] + x[I.dreb], 100) }),
  FX('ftr', 'FT rate', 'freethrows', { pub: true, def: 'Free-throw attempts per 100 field-goal attempts (FTA / FGA)', fn: o => R(o[I.fta], o[I.fga], 100) }),
  FX('ftmr', 'FTM rate', 'freethrows', { pub: true, def: "Free throws made per 100 field-goal attempts (Oliver's FTM / FGA)", fn: o => R(o[I.ftm], o[I.fga], 100) }),
  FX('ftp', 'FT%', 'freethrows', { pub: true, def: 'Free-throw %: FTM / FTA', fn: o => R(o[I.ftm], o[I.fta], 100) }),
  FX('p3r', '3PA rate', 'shooting', { pub: true, dir: 0, def: 'Share of field-goal attempts that are threes', fn: o => R(o[I.fg3a], o[I.fga], 100) }),
  FX('p3p', '3P%', 'shooting', { pub: true, def: 'Three-point %: 3PM / 3PA', fn: o => R(o[I.fg3m], o[I.fg3a], 100) }),
  FX('rimr', 'Rim rate', 'shooting', { pub: true, dir: 0, need: B.ZONES, def: 'Share of field-goal attempts at the rim (within 125 cm)', fn: o => R(o[I.rim_a], o[I.fga], 100) }),
  FX('rimp', 'Rim FG%', 'shooting', { pub: true, need: B.ZONES, def: 'Field-goal % at the rim', fn: o => R(o[I.rim_m], o[I.rim_a], 100) }),
  FX('midr', 'Mid-range rate', 'shooting', { pub: true, dir: 0, need: B.ZONES, def: 'Share of field-goal attempts that are twos away from the rim', fn: o => R(o[I.mid_a], o[I.fga], 100) }),
  FX('midp', 'Mid-range FG%', 'shooting', { pub: true, need: B.ZONES, def: 'Field-goal % on twos away from the rim', fn: o => R(o[I.mid_m], o[I.mid_a], 100) }),
  FX('astp', 'AST%', 'ball', { pub: true, def: 'Share of made field goals that were assisted (AST / FGM)', fn: o => R(o[I.ast], o[I.fgm], 100) }),
  FX('stlp', 'STL%', 'defence', { pub: true, def: 'Steals per 100 opponent possessions', fn: (o, x) => R(o[I.stl], x[I.poss_est], 100) }),
  FX('blkp', 'BLK%', 'defence', { pub: true, def: "Blocks per 100 of the opponent's two-point attempts", fn: (o, x) => R(o[I.blk], x[I.fga] - x[I.fg3a], 100) }),
  FX('ortg', 'Offensive rating', 'score', { unit: 'pts', score: true, def: 'Points per 100 possessions (counted possessions)', fn: o => R(o[I.pts], o[I.poss], 100) }),
  FX('ppp', 'Points per possession', 'score', { unit: 'pts', score: true, def: 'Points per counted possession', fn: o => R(o[I.pts], o[I.poss]) }),
  FX('paint', 'Paint points', 'score', { unit: 'pts', score: true, pub: true, pg: true, def: 'Points in the paint per game', fn: o => V(o[I.pts_paint]) }),
  FX('fast', 'Fast-break points', 'score', { unit: 'pts', score: true, pub: true, pg: true, def: 'Fast-break points per game', fn: o => V(o[I.pts_fast]) }),
  FX('second', 'Second-chance points', 'score', { unit: 'pts', score: true, pub: true, pg: true, def: 'Second-chance points per game', fn: o => V(o[I.pts_second]) }),
  FX('offto', 'Points off turnovers', 'score', { unit: 'pts', score: true, pub: true, pg: true, def: 'Points off turnovers per game', fn: o => V(o[I.pts_offto]) }),
  FX('bench', 'Bench points', 'score', { unit: 'pts', score: true, pub: true, pg: true, def: 'Bench points per game', fn: o => V(o[I.pts_bench]) }),
  // competitive time: the Explain inputs
  FX('c_efg', 'eFG% (competitive)', 'competitive', { def: 'eFG% with garbage-time possessions left out', fn: o => R(o[I.c_efgm], o[I.c_fga], 100) }),
  FX('c_tovp', 'TOV% (competitive)', 'competitive', { dir: -1, def: 'TOV% with garbage-time possessions left out', fn: o => R(o[I.c_tov], o[I.c_fga] + 0.44 * o[I.c_fta] + o[I.c_tov], 100) }),
  FX('c_orebp', 'OREB% (competitive)', 'competitive', { def: 'Share of own missed chances won back, garbage time out', fn: o => R(o[I.c_reb_off], o[I.c_reb_off] + o[I.c_reb_def], 100) }),
  FX('c_ftmr', 'FTM rate (competitive)', 'competitive', { def: 'Free throws made per 100 FGA, garbage time out', fn: o => R(o[I.c_ftm], o[I.c_fga], 100) }),
  FX('c_margin', 'Competitive margin', 'competitive', { unit: 'pts', side: 'game', diff: false, score: true, def: 'Points minus points allowed with garbage time out', fn: (o, x) => V(o[I.c_pts] - x[I.c_pts]) }),
  FX('garbage_share', 'Garbage-time share', 'competitive', { unit: 'share', dir: 0, def: 'Share of possessions played in garbage time', fn: o => R(o[I.g_poss], o[I.poss]) }),
  // tempo
  FX('pace', 'Pace', 'tempo', { unit: 'poss', dir: 0, side: 'game', diff: false, pub: true, def: 'Estimated possessions per 40 minutes, both sides averaged', fn: (o, x) => R(40 * (o[I.poss_est] + x[I.poss_est]) / 2, o[I.minutes]) }),
  FX('pace_x', 'Pace (counted)', 'tempo', { unit: 'poss', dir: 0, side: 'game', diff: false, def: 'Counted possessions per 40 minutes, both sides averaged', fn: (o, x) => R(40 * (o[I.poss] + x[I.poss]) / 2, o[I.minutes]) }),
  FX('pace3q', 'Pace (first 75%)', 'tempo', { unit: 'poss', dir: 0, side: 'game', diff: false, def: 'Possessions per 40 minutes over the first 75% of regulation', fn: (o, x) => R(40 * (o[I.poss_3q] + x[I.poss_3q]) / 2, 0.75 * o[I.reg_min]) }),
  FX('pace_own', 'Own pace', 'tempo', { unit: 'poss', dir: 0, pub: true, def: "The side's own estimated possessions per 40 minutes", fn: o => R(40 * o[I.poss_est], o[I.minutes]) }),
  FX('chances_pp', 'Chances per possession', 'tempo', { unit: 'n', dir: 0, def: 'Chances per possession (an offensive rebound starts a new chance)', fn: o => R(o[I.chances], o[I.poss]) }),
  FX('top_avg', 'Seconds per possession', 'time', { unit: 's', dir: 0, need: B.TIMED, def: 'Average time of possession, from gaining the ball to its last action', fn: o => R(o[I.timed_s], o[I.timed_n]) }),
  FX('top_share', 'Time of possession share', 'time', { unit: 'share', dir: 0, need: B.TIMED, def: 'Share of timed possession seconds that were this side\'s', fn: (o, x) => R(o[I.timed_s], o[I.timed_s] + x[I.timed_s]) }),
  FX('early_share', 'Early-clock share', 'time', { unit: 'share', dir: 0, need: B.TIMED, def: 'Share of timed first chances ending within 8 seconds', fn: o => R(o[I.fc_e_n], o[I.fc_n]) }),
  FX('late_share', 'Late-clock share', 'time', { unit: 'share', dir: 0, need: B.TIMED, def: 'Share of timed first chances ending after 16 seconds', fn: o => R(o[I.fc_l_n], o[I.fc_n]) }),
  FX('ppc_early', 'Points per chance, early', 'time', { unit: 'pts', need: B.TIMED, min: 5, def: 'Points per first chance ending within 8 seconds', fn: o => R(o[I.fc_e_pts], o[I.fc_e_n], 1, 5) }),
  FX('ppc_mid', 'Points per chance, 8-16 s', 'time', { unit: 'pts', need: B.TIMED, min: 5, def: 'Points per first chance ending 8 to 16 seconds in', fn: o => R(o[I.fc_m_pts], o[I.fc_m_n], 1, 5) }),
  FX('ppc_late', 'Points per chance, late', 'time', { unit: 'pts', need: B.TIMED, min: 5, def: 'Points per first chance ending after 16 seconds', fn: o => R(o[I.fc_l_pts], o[I.fc_l_n], 1, 5) }),
  FX('dreb_start', 'Possessions from a defensive rebound', 'time', { unit: 'share', dir: 0, need: B.TIMED, def: 'Share of possessions that began with a defensive rebound', fn: o => R(o[I.gain_dreb], o[I.poss]) }),
  // situations
  FX('tr_freq', 'Transition frequency', 'situations', { unit: 'share', dir: 0, need: B.SIT, def: 'Share of chances in transition', fn: o => R(o[I.tr_ch], o[I.sit_ch]) }),
  FX('tr_ppc', 'Transition points per chance', 'situations', { unit: 'pts', need: B.SIT, def: 'Points per transition chance', fn: o => R(o[I.tr_pts], o[I.tr_ch]) }),
  FX('hc_ppc', 'Half-court points per chance', 'situations', { unit: 'pts', need: B.SIT, def: 'Points per half-court chance', fn: o => R(o[I.hc_pts], o[I.hc_ch]) }),
  FX('sc_ppc', 'Second-chance points per chance', 'situations', { unit: 'pts', need: B.SIT, def: 'Points per second chance', fn: o => R(o[I.sc_pts], o[I.sc_ch]) }),
  FX('offto_ppc', 'Points per chance off turnovers', 'situations', { unit: 'pts', need: B.SIT, def: 'Points per chance after an opponent turnover', fn: o => R(o[I.offto_pts], o[I.offto_ch]) }),
  FX('sc_freq', 'Second-chance frequency', 'situations', { unit: 'share', dir: 0, need: B.SIT, def: 'Share of chances that were second chances', fn: o => R(o[I.sc_ch], o[I.sit_ch]) }),
  FX('ato_ppp', 'After-timeout points', 'situations', { unit: 'pts', need: B.SIT, min: 3, def: 'Points per possession after a timeout', fn: o => R(o[I.ato_pts], o[I.ato_n], 1, 3) }),
  FX('ast_share', 'Assisted share', 'ball', { unit: 'share', dir: 0, need: B.SIT, def: 'Share of made field goals that were assisted', fn: o => R(o[I.fgm_ast], o[I.fgm_ast] + o[I.fgm_unast]) }),
  FX('ast3_share', 'Assisted threes', 'ball', { unit: 'share', dir: 0, need: B.SIT, def: 'Share of made threes that were assisted', fn: o => R(o[I.fg3m_ast], o[I.fg3m]) }),
  // turnovers and fouls
  FX('live_share', 'Live-ball turnover share', 'turnovers', { unit: 'share', dir: -1, need: B.STL, def: 'Share of turnovers that were steals', fn: o => R(o[I.to_live], o[I.to_n]) }),
  FX('live100', 'Live-ball turnovers', 'turnovers', { unit: 'per 100', dir: -1, need: B.STL, def: 'Live-ball turnovers per 100 possessions', fn: o => R(o[I.to_live], o[I.poss], 100) }),
  FX('dead100', 'Dead-ball turnovers', 'turnovers', { unit: 'per 100', dir: -1, need: B.STL, def: 'Dead-ball turnovers per 100 possessions', fn: o => R(o[I.to_n] - o[I.to_live], o[I.poss], 100) }),
  FX('badpass100', 'Bad passes', 'turnovers', { unit: 'per 100', dir: -1, need: B.STYPE, def: 'Bad-pass turnovers per 100 possessions', fn: o => R(o[I.to_badpass], o[I.poss], 100) }),
  FX('handle100', 'Ball-handling turnovers', 'turnovers', { unit: 'per 100', dir: -1, need: B.STYPE, def: 'Travels, double dribbles and carries per 100 possessions', fn: o => R(o[I.to_handle], o[I.poss], 100) }),
  FX('offfoul100', 'Offensive fouls', 'turnovers', { unit: 'per 100', dir: -1, need: B.FOULKIND, def: 'Offensive-foul turnovers per 100 possessions', fn: o => R(o[I.to_offfoul], o[I.poss], 100) }),
  FX('foul100', 'Fouls committed', 'fouling', { unit: 'per 100', dir: -1, def: 'Fouls per 100 opponent possessions', fn: (o, x) => R(o[I.fouls], x[I.poss], 100) }),
  FX('sfoul_drawn100', 'Shooting fouls drawn', 'fouling', { unit: 'per 100', need: B.FOULKIND, def: 'Shooting fouls drawn per 100 possessions', fn: (o, x) => R(x[I.fouls_shooting], o[I.poss], 100) }),
  FX('trips100', 'Free-throw trips', 'freethrows', { unit: 'per 100', def: 'Trips to the line per 100 possessions', fn: o => R(o[I.ft_trips], o[I.poss], 100) }),
  FX('and1_rate', 'And-ones', 'freethrows', { unit: 'per 100', def: 'And-ones per 100 made field goals', fn: o => R(o[I.and1], o[I.fgm], 100) }),
  FX('bonus_share', 'Bonus free throws', 'freethrows', { unit: 'share', dir: 0, need: B.FOULKIND, def: 'Share of free-throw attempts from the bonus', fn: o => R(o[I.fta_bonus], o[I.fta]) }),
  FX('techs', 'Technicals', 'fouling', { unit: 'n', dir: -1, pg: true, def: 'Technical and unsportsmanlike fouls per game', fn: o => V(o[I.techs]) }),
  // flow and clutch
  FX('lead_changes', 'Lead changes', 'flow', { unit: 'n', dir: 0, side: 'game', diff: false, def: 'Times the lead changed hands', fn: o => V(o[I.lead_changes]) }),
  FX('ties', 'Ties', 'flow', { unit: 'n', dir: 0, side: 'game', diff: false, def: 'Times the score was level above 0-0', fn: o => V(o[I.ties]) }),
  FX('lead_share', 'Time ahead', 'flow', { unit: 'share', score: true, def: 'Share of the game spent ahead', fn: o => R(o[I.lead_ms], 60000 * o[I.minutes]) }),
  FX('max_lead', 'Largest lead', 'flow', { unit: 'pts', score: true, def: 'Largest lead, per game', fn: o => V(o[I.max_lead]) }),
  FX('max_deficit', 'Largest deficit', 'flow', { unit: 'pts', dir: -1, score: true, def: 'Largest deficit, per game', fn: o => V(o[I.max_deficit]) }),
  FX('best_run', 'Best run', 'flow', { unit: 'pts', score: true, def: 'Most consecutive points, per game', fn: o => V(o[I.best_run]) }),
  FX('runs8', 'Runs of 8+', 'flow', { unit: 'n', score: true, pg: true, def: 'Runs of eight or more unanswered points per game', fn: o => V(o[I.runs8]) }),
  FX('m_h1', 'First-half margin', 'flow', { unit: 'pts', score: true, pg: true, def: 'Points minus points allowed in the first half', fn: (o, x) => V(o[I.pts_h1] - x[I.pts_h1]) }),
  FX('m_h2', 'Second-half margin', 'flow', { unit: 'pts', score: true, pg: true, def: 'Points minus points allowed in the second half', fn: (o, x) => V(o[I.pts_h2] - x[I.pts_h2]) }),
  FX('m_ot', 'Overtime margin', 'flow', { unit: 'pts', score: true, pg: true, def: 'Points minus points allowed in overtime', fn: (o, x) => V(o[I.pts_ot] - x[I.pts_ot]) }),
  FX('cl_poss', 'Clutch possessions', 'clutch', { unit: 'n', dir: 0, pg: true, def: 'Possessions in the last 5 minutes or overtime within 5 points, per game', fn: o => V(o[I.cl_poss]) }),
  FX('cl_ppp', 'Clutch points per possession', 'clutch', { unit: 'pts', min: 4, def: 'Points per clutch possession', fn: o => R(o[I.cl_pts], o[I.cl_poss], 1, 4) }),
  FX('cl_tovp', 'Clutch TOV%', 'clutch', { dir: -1, def: 'Turnovers per 100 clutch possessions', fn: o => R(o[I.cl_tov], o[I.cl_poss], 100) }),
  FX('cl_efg', 'Clutch eFG%', 'clutch', { def: 'eFG% on clutch possessions', fn: o => R(o[I.cl_efgm], o[I.cl_fga], 100) }),
  FX('cl_ftr', 'Clutch FT rate', 'clutch', { def: 'Free-throw attempts per 100 FGA on clutch possessions', fn: o => R(o[I.cl_fta], o[I.cl_fga], 100) }),
  FX('cl_net100', 'Clutch net rating', 'clutch', { unit: 'pts', score: true, def: 'Clutch points minus points allowed per 100 clutch possessions', fn: (o, x) => R(o[I.cl_pts] - x[I.cl_pts], (o[I.cl_poss] + x[I.cl_poss]) / 2, 100) }),
  // rotation
  FX('players_used', 'Players used', 'rotation', { unit: 'n', dir: 0, def: 'Players who got on the floor', fn: o => V(o[I.players_used]) }),
  FX('rot_n', 'Rotation size', 'rotation', { unit: 'n', dir: 0, def: 'Players with ten minutes or more', fn: o => V(o[I.rot_n]) }),
  FX('top5_min_share', 'Top-five minutes share', 'rotation', { unit: 'share', dir: 0, def: 'Share of minutes played by the five most-used players', fn: o => V(o[I.top5_min_share]) }),
  FX('starters_min_share', 'Starters\' minutes share', 'rotation', { unit: 'share', dir: 0, need: B.STARTERS, def: 'Share of minutes played by the starting five', fn: o => V(o[I.starters_min_share]) }),
  FX('usg_hhi', 'Usage concentration', 'rotation', { unit: 'index', dir: 0, def: 'Herfindahl index of usage (100 = one player takes every shot)', fn: o => V(o[I.usg_hhi]) }),
  FX('top_usg_share', 'Top usage share', 'rotation', { unit: 'share', dir: 0, def: 'Share of usage taken by the busiest player', fn: o => V(o[I.top_usg_share]) }),
  FX('fives_used', 'Fives used', 'rotation', { unit: 'n', dir: 0, def: 'Different five-player lineups used', fn: o => V(o[I.fives_used]) }),
  FX('top_five_share', 'Top five\'s share', 'rotation', { unit: 'share', dir: 0, def: 'Share of minutes played by the most-used five', fn: o => V(o[I.top_five_share]) }),
  FX('starters_net', 'Starters\' plus-minus', 'rotation', { unit: 'pts', score: true, pg: true, need: B.STARTERS, def: 'Plus-minus of the starting five together, per game', fn: o => V(o[I.starters_net]) }),
  // builder-only: need the league's make rates (§7.11); derive() leaves them out
  FX('xefg', 'Expected eFG%', 'builder', { builder: true, def: 'eFG% expected from the shot mix at the league\'s make rates' }),
  FX('making', 'Shot-making', 'builder', { builder: true, unit: 'pp', def: 'eFG% above or below what the shot mix predicts' }),
  FX('xpts', 'Expected points', 'builder', { builder: true, unit: 'pts', score: true, def: 'Points expected from the attempts at the league\'s make rates' }),
  FX('luck_pts', 'Shooting luck', 'builder', { builder: true, unit: 'pts', score: true, def: 'Points minus expected points' })
];

/* which counts each factor reads, recorded once by running it on a probe */
(function recordUses() {
  const probe = (into) => new Proxy({}, { get: (_, k) => { const i = +k; if (Number.isInteger(i)) into.add(i); return 1; } });
  FACTOR_LIST.forEach(F => {
    const own = new Set(), opp = new Set();
    if (F.fn) { try { F.fn(probe(own), probe(opp)); } catch (_) { /* a probe never throws */ } }
    F.uses = { own: Array.from(own), opp: Array.from(opp) };
  });
})();
const FACTORS = Object.freeze(FACTOR_LIST.map(F => Object.freeze(Object.assign({}, F, { uses: Object.freeze(F.uses) }))));
const PUBLIC_KEYS = Object.freeze(['efg', 'ts', 'tovp', 'orebp', 'ftr', 'ftmr', 'ftp', 'p3r', 'p3p', 'rimr', 'rimp', 'midr', 'midp',
  'astp', 'stlp', 'blkp', 'pace', 'pace_own', 'paint', 'fast', 'second', 'offto', 'bench']);

const bitsOk = (F, qo, qx) => (F.need ? ((qo | 0) & F.need) === F.need && (qx == null || ((qx | 0) & F.need) === F.need) : true);
const readsOk = (F, o, x) => F.uses.own.every(i => isFinite(o[i])) && F.uses.opp.every(i => isFinite(x[i]));

/* one game: {k: value | null} */
function derive(own, opp, qOwn, qOpp) {
  const out = {};
  if (!own || !opp) return out;
  FACTORS.forEach(F => {
    if (!F.fn) return;
    if (!bitsOk(F, qOwn, qOpp) || !readsOk(F, own, opp)) { out[F.k] = null; return; }
    const v = F.fn(own, opp);
    out[F.k] = v == null || !isFinite(v) ? null : v;
  });
  return out;
}

/* a season (or a league, or a defence with the pairs swapped): {k: {v, n}}. For each factor the counts are
   summed over the games where both rows carry its need bits and every count it reads, the `mean` fields
   averaged over those games, then the formula applied once: a ratio of sums. A per-game factor is its sum
   divided by the games used. */
function seasonFactors(pairs) {
  const out = {};
  const list = pairs || [];
  FACTORS.forEach(F => {
    if (!F.fn) return;
    const so = new Float64Array(N), sx = new Float64Array(N);
    let n = 0;
    for (const p of list) {
      if (!p || !p.own || !p.opp) continue;
      if (!bitsOk(F, p.qOwn, p.qOpp) || !readsOk(F, p.own, p.opp)) continue;
      n++;
      for (const i of F.uses.own) so[i] += p.own[i];
      for (const i of F.uses.opp) sx[i] += p.opp[i];
    }
    if (!n) { out[F.k] = { v: null, n: 0 }; return; }
    MEAN.forEach(i => { so[i] /= n; sx[i] /= n; });
    let v = F.fn(so, sx);
    if (v != null && F.pg) v /= n;
    out[F.k] = { v: v == null || !isFinite(v) ? null : v, n };
  });
  return out;
}

/* a vector whose counts hang together (NaN is allowed: it is "not worked out", not wrong) */
function valid(x) {
  const a = x && x.length === undefined && x.f ? x.f : x;
  if (!a || a.length !== N) return false;
  const g = k => a[I[k]];
  const le = (lo, hi) => !(isFinite(g(lo)) && isFinite(g(hi))) || g(lo) <= g(hi) + 1e-9;
  for (let i = 0; i < N; i++) { const v = a[i]; if (v != null && typeof v === 'number' && isFinite(v) && v < 0 && !/^(starters_net)$/.test(LAYOUT[i].k)) return false; }
  return le('fgm', 'fga') && le('fg3m', 'fg3a') && le('fg3a', 'fga') && le('ftm', 'fta') && le('rim_m', 'rim_a') && le('mid_m', 'mid_a') &&
         le('to_live', 'to_n') && le('timed_n', 'poss') && le('cl_poss', 'poss') && le('g_poss', 'poss') && le('and1', 'ft_trips') &&
         le('trips_bonus', 'ft_trips') && le('poss_3q', 'poss');
}

return { FV, LAYOUT, INDEX, QBITS, FACTORS, PUBLIC_KEYS, CLUTCH_MS, CLUTCH_MARGIN, GARBAGE, BONUS, N,
         extract, toRows, fromRow, derive, seasonFactors, valid };
}));

/* ---------------------------------------------------------------------------
   GENERATED TAIL — do not edit this file. Edit the browser copy and re-run
   `node supabase/tests/extract-shared.mjs`; CI fails if the two drift.

   The UMD half above attaches to globalThis; this re-exports the same object
   so the Edge Function and the browser run one identical file.
   --------------------------------------------------------------------------- */
const __api = globalThis.EpinoiaFeatures;
export const { FV, LAYOUT, INDEX, QBITS, FACTORS, PUBLIC_KEYS, CLUTCH_MS, CLUTCH_MARGIN, GARBAGE, BONUS, N, extract, toRows, fromRow, derive, seasonFactors, valid } = __api;
export default __api;
