#!/usr/bin/env node
/* THE WEIGHTS THAT GO WITH THE SANS (epinoia/kit/profiletype.css, boxtype.css).

   The site's labels (--f-micro) and big figures and headings (--f-score) were drawn in two pixel faces whose letters are heavy by
   shape. A page that swaps both for Archivo (one variable face) keeps the rules' own weights, which were 400 because a pixel face
   has one: the same text comes out thin. This reads every CSS rule the page loads (its linked sheets and its own <style>), finds the
   ones that set a font through --f-score or --f-micro, and writes the matching weight beside it, under .ep-frame so it wins:
   figures and headings 700, labels 600 (a rule that already asks for a heavier weight is left alone).

     node tools/typeweights-gen.mjs            rewrite the generated block of both files
     node tools/typeweights-gen.mjs --check    exit 1 when a file is out of date (a CSS change that should have been regenerated)

   Pages: the player and club pages (profiletype.css, both faces), the game page (boxtype.css, labels only: its score numbers
   and league line keep the pixel faces). */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const BEGIN = '/* ==== GENERATED by tools/typeweights-gen.mjs: do not edit by hand ==== */';
const END = '/* ==== END GENERATED ==== */';

/* the rules of a stylesheet's text, [{ sel, body }], media blocks flattened, comments gone */
function rulesOf(css) {
  css = css.replace(/\/\*[\s\S]*?\*\//g, '');
  const out = [];
  (function walk(t) {
    let i = 0;
    while (i < t.length) {
      const o = t.indexOf('{', i);
      if (o < 0) break;
      let depth = 1, j = o + 1;
      while (j < t.length && depth) { if (t[j] === '{') depth++; else if (t[j] === '}') depth--; j++; }
      const head = t.slice(i, o).trim(), body = t.slice(o + 1, j - 1);
      if (/^@(media|supports)/i.test(head)) walk(body);
      else if (!/^@/.test(head)) out.push({ sel: head, body });
      i = j;
    }
  })(css);
  return out;
}
function sheetsOf(html, dir) {
  const css = [];
  for (const m of html.matchAll(/<link[^>]+href="([^"?#]+\.css)[^"]*"/g)) {
    const f = path.join(dir, m[1]);
    try { css.push(readFileSync(f, 'utf8')); } catch (_) { /* a font stylesheet elsewhere */ }
  }
  for (const m of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)) css.push(m[1]);
  return css.join('\n');
}
function weightOf(body) {
  const m = /(?:^|[;\s])font-weight\s*:\s*(\d+|bold|bolder|normal)/.exec(body);
  if (!m) return null;
  return m[1] === 'bold' || m[1] === 'bolder' ? 700 : m[1] === 'normal' ? 400 : +m[1];
}
function generate(pages, faces, prefix, minSize) {
  const want = { score: new Map(), micro: new Map() };
  for (const pg of pages) {
    const file = path.join(ROOT, pg), html = readFileSync(file, 'utf8');
    for (const { sel, body } of rulesOf(sheetsOf(html, path.dirname(file)))) {
      const ff = /font-family\s*:[^;]*var\(--f-(score|micro)\)/.exec(body) || /font\s*:[^;]*var\(--f-(score|micro)\)/.exec(body);
      if (!ff || !faces.includes(ff[1])) continue;
      const sz = /font-size\s*:\s*([\d.]+)px/.exec(body), w = weightOf(body), target = ff[1] === 'score' ? 700 : (sz && +sz[1] >= 12 ? 700 : 600);
      /* a page whose labels were sized for a wide pixel face (the scorer's 7px) is raised to minSize: the sans reads smaller at the same size */
      const needW = !(w != null && w >= target), needS = !!(minSize && sz && +sz[1] < minSize);
      if (!needW && !needS) continue;
      sel.split(',').map(s => s.trim()).filter(Boolean).forEach(s => {
        /* kept pixel: the top strip and the page index (the teletext layer), LIVE wherever it is a state (.bstate, .ep-live, a live card's
           status, the dashboard's count), the league tag and the scoreboard's numerals */
        if (/^(html|body|:root|\*)/.test(s) || /\.tt-line|\.tt-index|\.tt-ix|\.bt-kick|\.bscore|\.bstate|\.ep-live|\.fxc-st|\.fxd-n|#fxTabLive/.test(s)) return;
        want[ff[1]].set(s, { w: needW ? target : null, s: needS ? minSize : null });
      });
    }
  }
  const lines = [];
  for (const k of faces) {
    const sels = [...want[k].keys()].sort();
    if (!sels.length) continue;
    lines.push('/* ' + (k === 'score' ? 'figures and headings' : 'labels') + ': ' + sels.length + ' rules */');
    sels.forEach(s => { const v = want[k].get(s), d = []; if (v.w) d.push('font-weight:' + v.w + (k === 'score' ? ';font-stretch:94%' : '')); if (v.s) d.push('font-size:' + v.s + 'px'); lines.push(prefix + ' ' + s + '{' + d.join(';') + '}'); });
  }
  return lines.join('\n');
}
const JOBS = [
  { out: 'epinoia/kit/scorer-type.css', pages: ['epinoia/score/index.html'], faces: ['micro'], prefix: 'body', minSize: 9 },
  { out: 'epinoia/kit/clockcamtype.css', pages: ['epinoia/clockcam/index.html'], faces: ['micro'], prefix: 'body', minSize: 9 },
  { out: 'epinoia/kit/labeltype.css', pages: ['epinoia/admin/index.html', 'epinoia/admin/platform/index.html', 'epinoia/android/index.html', 'epinoia/api/index.html', 'epinoia/app/index.html', 'epinoia/broadcast/help/index.html', 'epinoia/community/index.html', 'epinoia/contact/index.html', 'epinoia/creators/hub/index.html', 'epinoia/creators/index.html', 'epinoia/creators/studio/index.html', 'epinoia/edit/index.html', 'epinoia/fan/index.html', 'epinoia/fixtures/index.html', 'epinoia/game/index.html', 'epinoia/games/index.html', 'epinoia/go/index.html', 'epinoia/go/nearby/index.html', 'epinoia/go/photos/index.html', 'epinoia/go/stamps/index.html', 'epinoia/home/index.html', 'epinoia/index.html', 'epinoia/injuries/index.html', 'epinoia/invite/index.html', 'epinoia/ios/index.html', 'epinoia/join/index.html', 'epinoia/l/index.html', 'epinoia/learn/index.html', 'epinoia/me/index.html', 'epinoia/news/index.html', 'epinoia/p/index.html', 'epinoia/privacy/index.html', 'epinoia/profile/index.html', 'epinoia/prophesy/index.html', 'epinoia/scouting/index.html', 'epinoia/signin/index.html', 'epinoia/stats/index.html', 'epinoia/stats/wowy/index.html', 'epinoia/t/index.html', 'epinoia/video/index.html', 'epinoia/votes/index.html', 'epinoia/winning/index.html'], faces: ['micro'], prefix: 'body' },
  { out: 'epinoia/kit/profiletype.css', pages: ['epinoia/p/index.html', 'epinoia/t/index.html'], faces: ['score', 'micro'], prefix: '.ep-frame' },
  { out: 'epinoia/kit/boxtype.css', pages: ['epinoia/game/index.html'], faces: ['score', 'micro'], prefix: 'body' }
];
let stale = 0;
for (const j of JOBS) {
  const file = path.join(ROOT, j.out);
  let cur = '';
  try { cur = readFileSync(file, 'utf8'); } catch (_) { cur = ''; }
  const nl = cur.includes('\r\n') ? '\r\n' : '\n', text = cur.replace(/\r\n/g, '\n');
  const a = text.indexOf(BEGIN), b = text.indexOf(END);
  const head = a >= 0 ? text.slice(0, a) : text.replace(/\s*$/, '\n');
  const next = head + BEGIN + '\n' + generate(j.pages, j.faces, j.prefix, j.minSize) + '\n' + END + '\n';
  if (next !== text) { stale++; if (!CHECK) writeFileSync(file, next.replace(/\n/g, nl)); }
}
if (CHECK) { if (stale) { console.error('typeweights-gen: out of date, run node tools/typeweights-gen.mjs'); process.exit(1); } console.log('typeweights-gen: up to date'); }
else console.log('typeweights-gen: wrote ' + JOBS.length + ' files');
